version: '3.8'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      container_name: postgres
      image: postgres:latest
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
      ports:
        - 5432:5432
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:21.1.2
      command: --debug start-dev
      restart: always
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres/keycloak
#        KC_DB_URL_HOST: postgres
#        KD_DB_URL_DATABASE: keycloak
#        KC_DB_SCHEMA:
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: keycloak
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: secret
        KEYCLOAK_ENVIRONMENT: "dev"
        DEBUG_PORT: "*:8787"
      ports:
        - 8080:8080
        - 8787:8787
      depends_on:
        - postgres

